import turtle
screen = turtle.Screen()
screen.bgcolor("yellow")
pen=turtle.Turtle()
pen.color("pink") 
pen.speed(5)
def draw_cube(size):
    for _ in range(4):
        pen.forward(size )
        pen.left(90)
    pen.right(45)
    pen.forward(size)
    pen.left(90)
    pen.forward(size)
    pen.left(90)
    pen.forward(size )
    pen.left(135)
    pen.forward(size)
    pen.left(90)
    pen.forward(size )
    pen.left(135)
    pen.forward(size)
    pen.left(90)
    pen.forward(size)
turtle.done()
